"""Add tables

Revision ID: 6c260cb3414d
Revises: a54e8b183bd9
Create Date: 2025-07-17 20:47:19.946349

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6c260cb3414d'
down_revision = 'a54e8b183bd9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
