"""Add tables

Revision ID: cd067fcf693b
Revises: 9e886c2a431d
Create Date: 2025-07-27 12:24:24.346228

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cd067fcf693b'
down_revision = '9e886c2a431d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbols', 'country')
    op.drop_column('symbols', 'currency')
    op.drop_column('symbols', 'industry')
    op.drop_column('symbols', 'exchange')
    op.drop_column('symbols', 'sector')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbols', sa.Column('sector', sa.VARCHAR(), nullable=True))
    op.add_column('symbols', sa.Column('exchange', sa.VARCHAR(), nullable=True))
    op.add_column('symbols', sa.Column('industry', sa.VARCHAR(), nullable=True))
    op.add_column('symbols', sa.Column('currency', sa.VARCHAR(), nullable=True))
    op.add_column('symbols', sa.Column('country', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
